"""Add debt column to Members model

Revision ID: 0bd0f28340b2
Revises: 
Create Date: 2024-03-09 17:54:56.109963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd0f28340b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('is_issued')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debt', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('debt')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_issued', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True))

    op.create_table('members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email_id', sa.VARCHAR(length=30), nullable=True),
    sa.Column('mobile_no', sa.INTEGER(), nullable=False),
    sa.Column('isMember', sa.BOOLEAN(), nullable=True),
    sa.Column('memberShip_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id'),
    sa.UniqueConstraint('memberShip_id')
    )
    # ### end Alembic commands ###
