"""Books model changed slightly

Revision ID: 9feaf19d31ad
Revises: 0499905615b5
Create Date: 2024-03-12 20:31:10.781131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9feaf19d31ad'
down_revision = '0499905615b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('authors',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('authors',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
