"""Books model pages

Revision ID: efaaf4f820ce
Revises: db4eb846e9c7
Create Date: 2024-03-13 12:43:52.542576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efaaf4f820ce'
down_revision = 'db4eb846e9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_pages', sa.Integer(), nullable=True))
        batch_op.drop_column('page')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page', sa.INTEGER(), nullable=True))
        batch_op.drop_column('num_pages')

    # ### end Alembic commands ###
